# Generated by Django 3.2.13 on 2022-05-09 10:13

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('IN', 'Входящий'), ('OUT', 'Исходящий')], max_length=20, null=True)),
                ('academic_year', models.CharField(blank=True, choices=[('2021 - 2022', '2021 - 2022'), ('2022 - 2023', '2022 - 2023')], max_length=20, null=True)),
                ('desired_specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.FileField(blank=True, null=True, upload_to=application.models.my_awesome_upload_function)),
                ('motivation', models.FileField(blank=True, null=True, upload_to=application.models.my_awesome_upload_function)),
                ('english', models.FileField(blank=True, null=True, upload_to=application.models.my_awesome_upload_function)),
                ('recommendation', models.FileField(blank=True, null=True, upload_to=application.models.my_awesome_upload_function)),
                ('status', models.CharField(choices=[('UN', 'Unreviewed'), ('AC', 'Accepted'), ('DE', 'Declined')], default='UN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.country')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
