# Generated by Django 3.2.13 on 2022-05-13 21:07

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_temporaryapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=application.models.my_awesome_upload_function),
        ),
    ]
