# Generated by Django 3.2.13 on 2022-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Unreviewed', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(blank=True, choices=[('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=20, null=True),
        ),
    ]
