# Generated by Django 3.2.13 on 2022-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220526_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='desired_specialty_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_specialty_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_specialty_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
