# Generated by Django 3.2.13 on 2022-05-09 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +9999999999 от 9 до 15 символо.', regex='^\\+?1?\\d{9,15}$')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=255, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('graduation_year', models.DateField(blank=True, null=True)),
                ('degree_title', models.CharField(blank=True, choices=[('BA', 'Bachelors degree'), ('MA', 'Masters degree')], max_length=255, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Паспорт ID должен состоять из цифр или букв алфавита', regex='^[a-zA-Z\\d0-20]*$')])),
                ('passport_authority', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('date_of_expiry', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +9999999999 от 9 до 15 символо.', regex='^\\+?1?\\d{9,15}$')])),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.country')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
