# Generated by Django 3.2.13 on 2022-05-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birth_date_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_person_email',
            new_name='contact_person_email_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_person_phone',
            new_name='contact_person_phone_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_person',
            new_name='contact_person_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='country_ci',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_expiry',
            new_name='date_of_expiry_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_issue',
            new_name='date_of_issue_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='degree_title',
            new_name='degree_title_ci',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='first_name_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='gender_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='graduation_year',
            new_name='graduation_year_ci',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='last_name_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='passport_authority',
            new_name='passport_authority_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='passport_id',
            new_name='passport_id_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='patronymic',
            new_name='patronymic_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_pi',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='specialty',
            new_name='specialty_ci',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='start_year',
            new_name='start_year_ci',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='university',
            new_name='university_ci',
        ),
    ]
