# Generated by Django 3.2.13 on 2022-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220526_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_expiry_pi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_issue_pi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduation_year_ci',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_year_ci',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
