# Generated by Django 3.2.13 on 2022-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220526_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_person_pi_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_person_pi_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_person_pi_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_title_ci_en',
            field=models.CharField(blank=True, choices=[('BA', 'Bachelors degree'), ('MA', 'Masters degree')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_title_ci_kk',
            field=models.CharField(blank=True, choices=[('BA', 'Bachelors degree'), ('MA', 'Masters degree')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_title_ci_ru',
            field=models.CharField(blank=True, choices=[('BA', 'Bachelors degree'), ('MA', 'Masters degree')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_pi_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_pi_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_pi_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_pi_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_pi_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_pi_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic_pi_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic_pi_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic_pi_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
